version: '3'
services:
  mysql-server:
    image: dorowu/onlyoffice-mysql:5.7.20
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
    networks:
     - internal
    stdin_open: true
    tty: true
    restart: always
    volumes:
     - mysql_data:/var/lib/mysql
  community-server:
    image: dorowu/onlyoffice-communityserver:9.6.1.627
    depends_on:
     - mysql-server
     - document-server
     - mail-server
    environment:
     - VIRTUAL_HOST=onlyoffice.your-domain.com
     - LETSENCRYPT_HOST=onlyoffice.your-domain.com
     - LETSENCRYPT_EMAIL=foo@bar.com
     - DOCUMENT_SERVER_PORT_80_TCP_ADDR=document-server
     - MYSQL_SERVER_ROOT_PASSWORD=my-secret-pw
     - MYSQL_SERVER_DB_NAME=onlyoffice 
     - MYSQL_SERVER_HOST=mysql-server 
     - MYSQL_SERVER_USER=onlyoffice_user
     - MYSQL_SERVER_PASS=onlyoffice_pass 
     - MAIL_SERVER_API_PORT=8081
     - MAIL_SERVER_API_HOST=mail-server
     - MAIL_SERVER_DB_HOST=mysql-server
     - MAIL_SERVER_DB_PORT=3306
     - MAIL_SERVER_DB_NAME=onlyoffice_mailserver
     - MAIL_SERVER_DB_USER=onlyoffice_mailserver_user
     - MAIL_SERVER_DB_PASS=onlyoffice_mailserver_user_pass
    networks:
     - internal
     - proxy
    stdin_open: true
    tty: true
    restart: always
    volumes:
     - community_data:/var/www/onlyoffice/Data
     - community_log:/var/log/onlyoffice
     - document_data:/var/www/onlyoffice/DocumentServerData
     - certs:/var/www/onlyoffice/Data/certs
  document-server:
    image: dorowu/onlyoffice-documentserver:5.1.2.9
    stdin_open: true
    tty: true
    restart: always
    networks:
      - internal
      - proxy
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
      - document_fonts:/usr/share/fonts/truetype/custom
      - document_forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten
    environment:
      - VIRTUAL_HOST=document.your-domain.com
      - LETSENCRYPT_HOST=document.your-domain.com
      - LETSENCRYPT_EMAIL=foo@bar.com
  mail-server:
    image: onlyoffice/mailserver:latest
    depends_on:
     - mysql-server
    hostname: onlyoffice.your-domain.com
    environment:
       - MYSQL_SERVER=mysql-server
       - MYSQL_SERVER_PORT=3306
       - MYSQL_ROOT_USER=onlyoffice_mailserver_user
       - MYSQL_ROOT_PASSWD=onlyoffice_mailserver_user_pass
       - MYSQL_SERVER_DB_NAME=onlyoffice_mailserver
    networks:
      - internal
    restart: always
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - mail_data:/var/vmail
      - mail_certs:/etc/pki/tls/mailserver
      - mail_log:/var/log
networks:
  internal:
    driver: 'bridge'
  proxy:
    external:
      name: proxy
volumes:
  mail_data:
  mail_certs:
  mail_log:
  document_data:
  document_log:
  document_forgotten:
  community_data:
  community_log:
  mysql_data:
  document_fonts:
  certs:
